add login view, routes and integration
wolox-training/jlr-react pull request #2
Opened 2022-06-23 15:32 UTC by joseleonardorojas

## Summary

* Add login view
* Add routes
* Add integration

## Screenshots

![image](https://user-images.githubusercontent.com/107204262/175399194-d2c9cf21-8f91-4212-936b-247d6de2ddc7.png)

![image](https://user-images.githubusercontent.com/107204262/175399277-7cc33965-078a-4c36-be09-17be70043dcd.png)

## Trello Card
https://trello.com/c/2NiTGo4s/12-login
https://trello.com/c/C37cBI8F/25-routing-i-router
https://trello.com/c/Ns5sVjsJ/23-sign-up-ii-integration
https://trello.com/c/Ipfy7HwB/45-react-query

2022-06-23 18:38 UTC, renzowolox requested changes

2022-06-23 18:38 UTC, renzowolox commented on src/components/Notification/styles.module.scss
> +  color: #d54f51;
Add the color to scss/variables/_colors.scss and use the constant added

2022-06-23 18:38 UTC, renzowolox commented on src/components/Notification/styles.module.scss
> +  color: #219256;
Same

2022-06-23 18:38 UTC, renzowolox commented on src/index.tsx
> +import 'scss/forms.scss';
Import form.scss into scss/application.scss like other sass files (components, layout, margins)

2022-06-23 18:38 UTC, renzowolox commented on src/screens/SignUp/index.tsx
> +    mutation.reset();
Reset should be called after the request finished, in case something needs to be fixed in the form.

2022-06-23 18:38 UTC, renzowolox commented on src/screens/SignUp/index.tsx
> +          <Notification message="Error al registrar usuario" type="error" />
Add i18n to message

2022-06-28 22:25 UTC, DavidRojas1612 approved these changes

2022-06-28 22:25 UTC, DavidRojas1612 commented on src/components/Notification/index.tsx
> +  return <div className={type === 'error' ? styles.msgError : styles.msgSuccess}>{ message }</div>;
install [clsx](https://www.npmjs.com/package/clsx) to make this validations

2022-07-15 14:43 UTC, merged