Session management
wolox-training/jlr-react pull request #3
Opened 2022-06-28 21:30 UTC by joseleonardorojas

## Summary

* Add book list view
* Routes
* Session management

problems
*typing of function parameters
*routes

## Screenshots

![image](https://user-images.githubusercontent.com/107204262/176301613-dd2d95c8-eadb-4227-8365-6720b961bdfe.png)

## Trello Card

https://trello.com/c/5hYMLKd2/15-session-management-logout
https://trello.com/c/fWYHxOxk/14-book-list-auth-header

2022-06-29 20:42 UTC, renzowolox requested changes

2022-06-29 20:42 UTC, renzowolox commented on src/components/App/index.tsx
> +          />
```suggestion
          <Route element={<PublicRoute />}>
            <Route path="/sign_up" element={<SignUp />}/>
            <Route path="/" element={<Login />}/>
          </Route>
```

2022-06-29 20:42 UTC, renzowolox commented on src/components/BookList/index.tsx
> +        books.map((todo: IBook) => (
```suggestion
        books.map((book: IBook) => (
```
Use more descriptive names

2022-06-29 20:42 UTC, renzowolox commented on src/components/BookList/styles.module.scss
> +  font-size: 16px;
Sort

2022-06-29 20:42 UTC, renzowolox commented on src/components/BookList/styles.module.scss
> +  color: #828282;
use color variable

2022-06-29 20:42 UTC, renzowolox commented on src/components/NavBar/index.tsx
> +        Logout
Add i18n

2022-06-29 20:42 UTC, renzowolox commented on src/components/Notification/index.tsx
> +export default Notification;
Add empty line

2022-06-29 20:42 UTC, renzowolox commented on src/components/PrivateRoute/index.tsx
> +function Notification({ children }: any) {
Why is it called Notification?

2022-06-29 20:42 UTC, renzowolox commented on src/components/PublicRoutes/index.tsx
> +export default Notification;
```suggestion
import React from 'react';
import { Navigate, Outlet } from 'react-router-dom';

import { isAuthenticated } from 'utils/sessionManagement';

function PublicRoutes() {
  if (isAuthenticated()) {
    return <Navigate to="/home" replace />;
  }
  
  return <Outlet />;
}

export default PublicRoutes;
```

2022-06-29 20:42 UTC, renzowolox commented on src/screens/SignUp/index.tsx
> +import Notification from '../../components/PrivateRoute/index';
why replaced Notification with PrivateRoute component?

2022-06-30 20:04 UTC, betoobernal commented on src/components/App/index.tsx
>            <Route path="*" element={<div>No found</div>} />
use i18n

2022-06-30 20:04 UTC, betoobernal commented on src/components/BookList/styles.module.scss
> +.cardBook {
use kebab-case

2022-06-30 20:06 UTC, betoobernal commented on src/components/NavBar/index.tsx
> +    navigate('/', { replace: true });
i suppose we could use a constant file for this

2022-07-15 14:38 UTC, merged